# Generated by Django 5.2.16 on 2026-07-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('files_downloaded', models.IntegerField(default=0)),
                ('files_opened', models.IntegerField(default=0)),
                ('usb_connected', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_outside_office', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('risk_score', models.IntegerField(default=0)),
                ('threat_level', models.CharField(choices=[('SAFE', 'Safe'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='SAFE', max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='myapp.useractivity')),
            ],
        ),
    ]
